### ISSUE TITLE
No aparecen las burbujas?

### ISSUE THREAD

**Issue by LolbitSL28** [LolbitSL28/MyM2#3]
![image](https://user-images.githubusercontent.com/106454523/202627364-31d753ab-5420-498d-a5cc-84a052bf5f87.png)

no me aparecen las burbujas, pero el home ya sale solo una vez que entras en vez del inicio de cakephp :D

**Comment by StiffChick** [comment]
alatorre- ._.

**Comment by AlonsoBujanda** [comment]
Ya lo arregle agregando las imagenes a la misma carpeta del css

**Comment by LolbitSL28** [comment]
ya hiciste el commit?

**Comment by LolbitSL28** [comment]
![image](https://user-images.githubusercontent.com/106454523/202630552-40557eb2-bd7b-4e5c-a1ea-a1f42bc0d379.png)

aun no me salen si es que ya hiciste el commit

**Comment by LolbitSL28** [comment]
![image](https://user-images.githubusercontent.com/106454523/202630713-ce680728-5ca3-40d2-88a9-79d606f3f470.png)

olvidalo, ya salio, ocupaba darle fetch xd
