### ISSUE TITLE
Acceso solo empleados

### ISSUE THREAD

**Issue by LolbitSL28** [LolbitSL28/MyM2#8]
Weno esto es algo con lo que tambien nos topamos el semestre pasado. Obviamente los usuarios no pueden tener acceso a cosas a las cuales se supone que solo los empleados deben de accesar,  como agregar articulos y asi. Tengo planeado hacer algun tipo de cuenta de admin la cual es la unica que puede accesar al crud de los empleados.  El empleado deberia crearse una cuenta como si fuera cualquier otro usuario y por medio del id_usuario, el admin agregaria a sus empleados. Cualquier usuario que pertenezca a la tabla de empleados podra accesar a las partes de la pagina que es solo para empleados. 

En teoria (y lo que yo me imagino deberia de suceder), es que si haces log in con una cuenta que pertenece a la tabla de empleados, en la pagina vas a poder visualizar las cosas que un usuario comun no puede, es decir, la pagina de inicio y todas sus funciones no podran ser visibles por todo el mundo y simplemente no ser accesadas o que te de un error. Claro que podriamos hacer eso y facilirnos la vida, pero siento que hacer eso no es muy profesional que digamos. Pasaria lo mismo con la de admin, la cuenta del admin es la unica la cual puede ver la opcion del crud de empleados; los empleados no podrian visualizar eso.

Como se hace eso? Quien sabe pero pues es lo que se ocupa.

**Comment by LolbitSL28** [comment]
Ok, ahora que lo estoy pensando, deberiamos hacer una sola seccion en donde venga incluido **todo** lo que van a estar los empleados y el admin usando

**Comment by AlonsoBujanda** [comment]
Yo me encargo de eso......haber si no truena x,D

**Comment by AlonsoBujanda** [comment]
Ok ya no entendi nada..... .____."

**Comment by LolbitSL28** [comment]
que paso?
